# Generated by Django 3.0.3 on 2020-03-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urltable',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
